<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="AS-PC-23" failures="1" tests="6" name="testcases.projects.CreateProjectMemberTestCases" time="0.474" errors="0" timestamp="2025-02-04T11:55:35 IST" skipped="0">
  <testcase classname="testcases.projects.CreateProjectMemberTestCases" name="verifyCreateProjectMember" time="0.089"/>
  <system-out/>
  <testcase classname="testcases.projects.CreateProjectMemberTestCases" name="verifyCreateProjectMemberWithInvalidResourceId" time="0.159"/>
  <system-out/>
  <testcase classname="testcases.projects.CreateProjectMemberTestCases" name="verifyCreateProjectMemberWithInvalidProjectIds" time="0.109">
    <failure message="Expected failure with invalid project ID: 12345 did not expect [200] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Expected failure with invalid project ID: 12345 did not expect [200] but found [200]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failEquals(Assert.java:1417)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:156)
at org.testng.Assert.assertNotEquals(Assert.java:2033)
at testcases.projects.CreateProjectMemberTestCases.verifyCreateProjectMemberWithInvalidProjectIds(CreateProjectMemberTestCases.java:95)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyCreateProjectMemberWithInvalidProjectIds -->
  <system-out/>
  <testcase classname="testcases.projects.CreateProjectMemberTestCases" name="verifyCreateProjectMemberWithInvalidAccessToken" time="0.042"/>
  <system-out/>
  <testcase classname="testcases.projects.CreateProjectMemberTestCases" name="verifyCreateProjectMemberWithInvalidTenantId" time="0.040"/>
  <system-out/>
  <testcase classname="testcases.projects.CreateProjectMemberTestCases" name="verifyCreateProjectMemberWithoutAccessToken" time="0.035"/>
  <system-out/>
</testsuite> <!-- testcases.projects.CreateProjectMemberTestCases -->
